version: '3'
services:
    letsencryptgo:
        image: goacme/lego
        container_name: lego
        volumes:
            - /home/pi/app_data:/var/lib
        environment:
            DUCKDNS_TOKEN: ${USER_DUCKDNS_TOKEN}
        command: ["lego", "--accept-tos", "--path", "/var/lib/", "--email", "${USER_EMAIL}", "--dns", "duckdns", "--domains", "${USER_HOSTNAME}", "--domains", "*.${USER_HOSTNAME}", "renew"]
    controller:
        restart: always
        image: yalmannaee/peltier-controller:latest
        container_name: peltier_controller
        ports:
            - "80:80"
            - "443:443"
        devices:
            - "/dev/gpiomem:/dev/gpiomem"
        volumes:
            - /home/pi/app_data:/var/lib/peltier_controller
        environment:
            HOSTNAME: "${USER_HOSTNAME}"
    # By default we assume you're using DuckDNS.org (https://www.duckdns.org)
    # as a hostname. The letsencryptgo service issues an encryption certificate in that domain's name