version: '3'
services:
    letsencryptgo:
        image: goacme/lego:latest
        container_name: lego
        environment:
            DUCKDNS_TOKEN: ${USER_DUCKDNS_TOKEN}
        command: ["lego", "--email", "${USER_EMAIL}", "--dns", "duckdns", "--domains", "${USER_HOSTNAME}", "*.${USER_HOSTNAME}", "run"]
    controller:
        restart: always
        image: yalmannaee/peltier-controller:latest
        container_name: peltier_controller
        ports:
            - "80:80"
            - "443:443"
        devices:
            - "/dev/gpiomem:/dev/gpiomem"
        volumes:
            - ~/app_data:/var/lib/peltier_controller
        environment:
            HOSTNAME: "${USER_HOSTNAME}"
    # By default we assume you're using DuckDNS.org (https://www.duckdns.org)
    # as a hostname. The below issues an encryption certificate in that domain's name