version: '3'
services:
    letsencryptgo:
        image: goacme/lego:latest
        container_name: lego
        environment:
            DUCKDNS_TOKEN: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        command: ["lego", "--email", "myemail@example.com", "--dns", "duckdns", "--domains", "peltier_controller.duckdns.org", "run"]
    controller:
        restart: always
        image: yalmannaee/peltier-controller:latest
        container_name: peltier_controller
        network_mode: "host"
        privileged: true
        volumes:
            - ~/app_data:/var/lib/peltier_controller
        environment:
            HOSTNAME: peltier_controller.duckdns.org
    # By default we assume you're using DuckDNS.org (https://www.duckdns.org)
    # as a hostname. The below issues an encryption certificate in that domain's name