# This is a basic workflow to help you get started with Actions

name: CI SvelteKit Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build redistimeseries.so
        run: |
          git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git
          cd RedisTimeSeries
          make setup
          make build

      # Add Node site
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - run: npm ci
        working-directory: ./docker-src/site-src
      - run: npm run build
        working-directory: ./docker-src/site-src
      - run: zip -r build.zip build package.json package-lock.json
        working-directory: ./docker-src/site-src

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./docker-src/site-src/build.zip
            ./RedisTimeSeries/bin/redistimeseries.so          
